name: Rubocop

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rubocop
      uses: andrewmcodes/rubocop-linter-action@v3.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
